flags: {}
extra-package-dbs: []
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
        url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
        sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9
compiler-check: match-exact
package-indices:
- name: HackageOrig
  http: https://hackage.haskell.org/00-index.tar.gz
  download-prefix: https://hackage.haskell.org/package/
resolver: lts-7.19

packages:
- location: '.'
- location:
    git: https://github.com/reflex-frp/reflex
    commit: 91299fce0bb2caddfba35af6608df57dd31e3690
    # Latest develop comment at the time I stole this code
  extra-dep: true
- location:
    git: https://github.com/hamishmack/reflex-dom
    commit: d9842742183a800cf1f98f89d42d849d52dd2d67
    # Latest develop comment at the time I stole this code
  extra-dep: true

extra-deps:
  - bizzlelude-js-1.0.4
  - ghcjs-dom-0.7.0.3
  - ghcjs-dom-jsaddle-0.7.0.3
  - ghcjs-dom-jsffi-0.7.0.3
  - jsaddle-0.7.0.0
  - jsaddle-dom-0.7.0.3
  - jsaddle-warp-0.7.0.0
  - prim-uniq-0.1.0.1
  - ref-tf-0.4.0.1
  - zenc-0.1.1
