flags: {}
extra-package-dbs: []
packages:
- '.'
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006030_ghc-7.10.3:
        url: http://ghcjs.tolysz.org/lts-6.30-9006030.tar.gz
        sha1: 2371e2ffe9e8781808b7a04313e6a0065b64ee51
extra-deps:
- bizzlelude-0.0.3
compiler-check: match-exact
package-indices:
- name: HackageOrig
  http: https://hackage.haskell.org/00-index.tar.gz
  download-prefix: https://hackage.haskell.org/package/
compiler: ghcjs-0.2.0.9006030_ghc-7.10.3
resolver: lts-6.30
