flags: {}
extra-package-dbs: []
packages:
  - .
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
        url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
        sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9
extra-deps:
  - bizzlelude-1.0.3
  - directory-1.3.0.2
  - ghcjs-dom-0.9.1.1
  - ghcjs-dom-jsffi-0.9.1.1
compiler-check: match-exact
package-indices:
- name: HackageOrig
  http: https://hackage.haskell.org/00-index.tar.gz
  download-prefix: https://hackage.haskell.org/package/
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
resolver: lts-7.19
